add README to contrib
due to manually adding dependencies to some of the files, I modified
the script so it would just run the `append_readme` function. If
we want to re-generate these from scratch in the future we'll need to
manually re-add the dependencies.

diff --git a/util/generate-contrib b/util/generate-contrib
--- a/util/generate-contrib
+++ b/util/generate-contrib
@@ -13,13 +13,13 @@ PGVERSION=$1
 REVISION=${2:-0}
 
 function generate_yaml() {
-  dir=$1
-  ext=$2
-  comment=$3
-  slug=$4
+  ext=$1
+  comment=$2
+  slug=$(detect_slug $ext)
   pg_major_version=$(echo $PGVERSION | cut -d . -f 1)
+  output_file="out/${ext}.yaml"
   echo "generating $ext..."
-  cat <<EOF >out/$ext.yaml
+  cat <<EOF >$output_file
 apiVersion: v1
 name: $ext
 version: "$PGVERSION.$REVISION"
@@ -44,7 +44,58 @@ build:
 pgVersions:
   - "$pg_major_version"
 EOF
+
+  append_readme $slug $output_file
 }
+
+function require_util() {
+  which -s $1 || (echo "$1 is required" && exit 1)
+}
+
+function append_readme() {
+  slug=$1
+  output_file=$2
+
+  cat <<EOF >>$output_file
+readme: |
+  For formatted documentation, please see https://www.postgresql.org/docs/15/$slug.html.
+
+  \`\`\`
+EOF
+
+  lynx -dump ./postgresql-$PGVERSION/doc/src/sgml/html/$slug.html \
+    | gsed -E -e '/References/,$d' -e 's/\[[0-9]+\]//g' -e 's/^/  /' \
+    >>$output_file
+
+  echo '  ```' >>$output_file
+}
+
+function detect_slug() {
+  ext=$1
+  slug=$(echo $ext | tr _ -)
+  try_slug $slug && echo $slug && return
+  slug=$(echo $ext | tr -d _)
+  try_slug $slug && echo $slug && return
+}
+
+function try_slug() {
+  slug=$1
+  test -f ./postgresql-$PGVERSION/doc/src/sgml/html/$slug.html
+  return $?
+}
+
+require_util wget
+require_util lynx
+require_util tar
+require_util sed
+require_util grep
+require_util tr
+
+if [ -z "$1" ]; then
+  echo 'first argument (PGVERSION) is required' && exit 1
+fi
+
+SED=$(which -s gsed && echo gsed || echo sed)
 
 mkdir -p out
 rm -f out/unable.txt
@@ -58,11 +109,10 @@ for dir in $(find ./postgresql-$PGVERSION/contrib -type d -depth 1)
 do
   ext=$(basename $dir)
   if [ -f $dir/$ext.control ]; then
-    comment=$(cat $dir/$ext.control | grep ^comment | cut -f 2 -d = | sed -E 's/^ +//' | tr -d \')
-    slug=$(echo $ext | tr -d _)
-    requires=$(cat $dir/$ext.control | grep ^requires | cut -f 2 -d = | sed -E 's/^ +//' | tr -d \')
+    comment=$(cat $dir/$ext.control | grep ^comment | cut -f 2 -d = | $SED -E 's/^ +//' | tr -d \')
+    requires=$(cat $dir/$ext.control | grep ^requires | cut -f 2 -d = | $SED -E 's/^ +//' | tr -d \')
     if [ -z "$requires" ]; then
-      generate_yaml $dir $ext "$comment" $slug
+      generate_yaml $ext "$comment"
     else
       echo unable to process $ext: has dependencies >&2
       echo $ext >> out/unable.txt
